version: "3.5"

services:
  api01: 
    build : .
    hostname: api01
    restart: unless-stopped
    networks:
      - default
    environment:
      - APP_PORT=3000
      - DATABASE_URL=postgres://projectmanager:projectmanager@db:5432?sslmode=disable
    depends_on:
      - db

  db:
    hostname: db
    networks: 
      - default
    image: postgres:16
    environment:
      - POSTGRES_USER=projectmanager 
      - POSTGRES_PASSWORD=projectmanager 
      - POSTGRES_DB=projectmanager 
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database//postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf 

     
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1.0GB

networks:
  default:
